version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    networks: [devnet]
    env_file:
      - .env
    environment:
      PORT: 4000
      DB_HOST: postgres        # dùng tên service bên infra
      DB_PORT: 5432
      DB_NAME: erp
      DB_USERNAME: app
      DB_PASSWORD: app
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
      - backend_node_modules:/app/node_modules

networks:
  devnet:
    external: true  # join vào network 'devnet' đã tồn tại
volumes:
  backend_node_modules: {}