version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: erp
    ports: ["5432:5432"]
    volumes: ["pg:/var/lib/postgresql/data"]
    networks: [devnet]

  redis:
    image: redis:7
    ports: ["6379:6379"]
    networks: [devnet]
    command: redis-server --appendonly yes
    volumes: ["redis:/data"]

volumes:
  pg:
  redis:

networks:
  devnet:
    name: devnet  # đặt tên cố định để stack khác join vào